### PR TITLE
TS-2078: add more eslint rules

### PR DESCRIPTION
**Pull request by rokasAt10speed**
**Task:**
- https://10speed.atlassian.net/browse/TS-2078

**Description**
Added the following rules to config:
- [no-nested-ternary - ESLint - Pluggable JavaScript Linter](https://eslint.org/docs/latest/rules/no-nested-ternary)
- [no-unneeded-ternary - ESLint - Pluggable JavaScript Linter](https://eslint.org/docs/latest/rules/no-unneeded-ternary)
- [no-empty-pattern - ESLint - Pluggable JavaScript Linter](https://eslint.org/docs/latest/rules/no-empty-pattern)
- [no-useless-rename - ESLint - Pluggable JavaScript Linter](https://eslint.org/docs/latest/rules/no-useless-rename)
- [prefer-const - ESLint - Pluggable JavaScript Linter](https://eslint.org/docs/latest/rules/prefer-const)
- [no-useless-return - ESLint - Pluggable JavaScript Linter](https://eslint.org/docs/latest/rules/no-useless-return)
- [no-var - ESLint - Pluggable JavaScript Linter](https://eslint.org/docs/latest/rules/no-var)

### CODE REVIEW

**Comment by emiliskiskis** [comment]
can we also add `quotes: [2, 'double', {allowTemplateLiteral:false, avoidEscape:true}]`?

**Comment by rokasAt10speed** [comment]
> can we also add `quotes: [2, 'double', {allowTemplateLiteral:false, avoidEscape:true}]`?

@emiliskiskis Prettier already handles quotes with auto formatting

**Comment by rokasAt10speed** [comment]
> can we also add `quotes: [2, 'double', {allowTemplateLiteral:false, avoidEscape:true}]`?

@emiliskiskis also rule `quotes` has been deprecated by eslint https://eslint.org/docs/latest/rules/quotes and moved to a separated stylistic plugin. Anyways, as mentioned, prettier already handles that part for us, so it's not that necessary to offload that to eslint.

**Review by emiliskiskis — APPROVED** [review]
I wanted to make useless template strings an error, but oh well 🤷‍♀️

**Pull request merged**
